# Generated by Django 2.1.5 on 2019-01-21 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190122_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성된 날짜'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성된 날짜'),
        ),
    ]
